name: CI

on:
  push:
    branches:
      - master

env:
  DOCUMENTATION_CNAME: 'pprofizi.github.io/test_CICD'

jobs:
  docs:
    name: "Documentation"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.10

      - name: "Setup headless display"
        uses: pyvista/setup-headless-display-action@v1

      - name: "Setup Graphviz"
        uses: ts-graphviz/setup-graphviz@v1

#      - name: "Install OS packages"
#        run: |
#          choco install pandoc

      - name: "Install documentation packages for Python"
        run: |
          pip install -r requirements/requirements_docs.txt

      - name: "List installed packages"
        shell: bash
        run: pip list

      - name: "Build HTML Documentation"
        shell: cmd
        working-directory: .ci
        run: |
          build_doc.bat
        timeout-minutes: 10

      - name: "Zip HTML Documentation"
        shell: pwsh
        run: |
          Compress-Archive -Path docs/build/html/* -Destination HTML-doc.zip
        if: always()

      - name: "Upload HTML Documentation"
        uses: actions/upload-artifact@v3
        with:
          name: HTML-doc.zip
          path: HTML-doc.zip
        if: always()

  upload-development-docs:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [docs]
    steps:
      - name: "Upload development documentation"
        uses: ansys/actions/doc-deploy-dev@v4
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          doc-artifact-name: HTML-doc.zip